2024-06-13 00:48:44,288 ERROR: Exception on /user/user1/funds [GET] [in /Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/.conda/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ender/Workspace/PythonExperiment/server/app/routes.py", line 426, in get_user_funds
    funds_list = [
                 ^
  File "/Users/ender/Workspace/PythonExperiment/server/app/routes.py", line 433, in <listcomp>
    'id': manager.id,
          ^^^^^^^
NameError: name 'manager' is not defined
2024-06-13 00:49:00,105 INFO: Flask startup [in /Users/ender/Workspace/PythonExperiment/server/app/__init__.py:44]
2024-06-13 00:56:59,318 INFO: Flask startup [in /Users/ender/Workspace/PythonExperiment/server/app/__init__.py:44]
2024-06-13 10:28:25,976 INFO: Flask startup [in /Users/ender/Workspace/PythonExperiment/server/app/__init__.py:44]
